name: Compile Quake 2 on Windows using MinGW

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install MinGW
      run: |
        choco install mingw

    - name: Add MinGW to PATH
      run: |
        echo "C:\tools\mingw64\bin" >> $env:GITHUB_PATH

    - name: Compile Quake 2 Source Code
      run: |
        mingw32-make

    - name: Archive Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: quake2-build-windows
        path: |
          **/*.exe
          **/*.dll
