name: Compile Quake 2 on Windows with CMake and Visual Studio 2022

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install CMake
      run: choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System'

    - name: Set up MSBuild
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Generate Project Files with CMake
      run: |
        mkdir build
        cd build
        cmake .. -G "Visual Studio 17 2022"

    - name: Compile Quake 2 Source Code
      run: |
        cd build
        msbuild Quake2.sln /p:Configuration=Release /p:Platform=x64

    - name: Archive Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: quake2-build-windows
        path: |
          build/**/*.exe
          build/**/*.dll
